wandb_version: 1

bs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.15.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695746727.818243
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 7
      - 16
      - 23
      - 38
      4: 3.9.18
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: epoch/epoch
      6:
      - 3
